
import java.util.ArrayList;
import java.util.List;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JOptionPane;
import model.Bobot;
import model.HiddenNode;
import model.InputNode;
import model.OutputNode;
import model.TargetNode;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * simulasi.java
 *
 * Created on Oct 23, 2013, 4:35:53 PM
 */
/**
 *
 * @author Aniq
 */
public class simulasi extends javax.swing.JFrame {

    /**
     * Creates new form simulasi
     */
    public simulasi() {
        initComponents();
       
        this.setTitle("Training Demo Single & Multy Layer Perceptron");
    }
    public int[][] input;
    public int[] target;
    public int threshold;
    public double w1_final;
    public double w2_final;
    public double alpha;
    public simulasi m;
    public int tipe;
    public static int INTERVAL = 2;//detik
    public int error = 0;
    public int errorcount = 4;
    public int maxLoop = 0;
    public int epoch = 1;
    public int i = 0;
    
    
    public List<InputNode> inputnode;
    public List<HiddenNode> hidden;
    public List<OutputNode> output;
    public List<Bobot> bobotHide;
    public List<Bobot> bobotOut;
    public List<TargetNode> targetnode;
    public int[][] inputArray;
    public int[][] targetArray;
    public boolean status=false;
    public int in=0;

     /**
     * @return the input
     */
    public int[][] getInput() {
        return input;
    }

    /**
     * @param input the input to set
     */
    public void setInput() {
        this.input = new int[][]{{1, 1}, {1, 0}, {0, 1}, {0, 0}};
    }

    /**
     * @return the threshold
     */
    public int getThreshold() {
        return threshold;
    }

    /**
     * @param threshold the threshold to set
     */
    public void setThreshold(int threshold) {
        this.threshold = threshold;
    }

    /**
     * @return the w1
     */
    public double getW1() {
        return w1_final;
    }

    /**
     * @param w1 the w1 to set
     */
    public void setW1(double w1) {
        this.w1_final = w1;
    }

    /**
     * @return the w2
     */
    public double getW2() {
        return w2_final;
    }

    /**
     * @param w2 the w2 to set
     */
    public void setW2(double w2) {
        this.w2_final = w2;
    }

    /**
     * @return the alpha
     */
    public double getAlpha() {
        return alpha;
    }

    /**
     * @param alpha the alpha to set
     */
    public void setAlpha(double alpha) {
        this.alpha = alpha;
    }

    /**
     * @return the target
     */
    public int[] getTarget() {
        return target;
    }

    /**
     * @param target the target to set
     */
    public void setTarget(int[] target) {
        this.target = target;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        background1 = new background();
        jLabel4 = new javax.swing.JLabel();
        txt_x1_or = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_alpha_or = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_th_or = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_error_or = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_w1_or = new javax.swing.JTextField();
        txt_w2_or = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_x2_or = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_x1w1_or = new javax.swing.JTextField();
        txt_x2w2_or = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_f_or = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_y_or = new javax.swing.JTextField();
        training_or = new javax.swing.JButton();
        lbl_epoch = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        backgroundxor1 = new backgroundxor();
        txt_x1_xor = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        txt_x2_xor = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        txt_h2_xor = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        txt_h1_xor = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        txt_out_xor = new javax.swing.JTextField();
        txt_target_xor = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        txt_alpha_xor = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        txt_th_xor = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txt_w11_xor = new javax.swing.JTextField();
        txt_w21_xor = new javax.swing.JTextField();
        txt_w12_xor = new javax.swing.JTextField();
        txt_w22_xor = new javax.swing.JTextField();
        txt_w32_xor = new javax.swing.JTextField();
        txt_w31_xor = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        txt_error_xor = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setText("X1");

        jLabel1.setText("alpha");

        jLabel2.setText("treshold");

        jLabel3.setText("error");

        txt_error_or.setEditable(false);
        txt_error_or.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setText("W1");

        jLabel7.setText("W2");

        jLabel5.setText("X2");

        jLabel8.setText("X1.W1");

        txt_x1w1_or.setEditable(false);
        txt_x1w1_or.setBackground(new java.awt.Color(255, 255, 255));

        txt_x2w2_or.setEditable(false);
        txt_x2w2_or.setBackground(new java.awt.Color(255, 255, 255));
        txt_x2w2_or.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_x2w2_orActionPerformed(evt);
            }
        });

        jLabel9.setText("X2.W2");

        jLabel10.setText("f(y)");

        txt_f_or.setEditable(false);
        txt_f_or.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setText("Y");

        txt_y_or.setEditable(false);
        txt_y_or.setBackground(new java.awt.Color(255, 255, 255));

        training_or.setText("TRAINING");
        training_or.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                training_orActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "OR", "AND", "ANDNOT" }));

        javax.swing.GroupLayout background1Layout = new javax.swing.GroupLayout(background1);
        background1.setLayout(background1Layout);
        background1Layout.setHorizontalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(background1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel4)
                        .addGap(49, 49, 49)
                        .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txt_w1_or, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_w2_or, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(background1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txt_x2_or, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_x1_or, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(background1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(background1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addContainerGap())
                            .addGroup(background1Layout.createSequentialGroup()
                                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_x1w1_or)
                                    .addComponent(txt_x2w2_or, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txt_f_or, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(93, 93, 93))
                                    .addGroup(background1Layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lbl_epoch, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)))
                                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(background1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txt_y_or, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(81, 81, 81))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_error_or, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_alpha_or, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_th_or, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(232, 232, 232))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background1Layout.createSequentialGroup()
                        .addComponent(training_or)
                        .addGap(215, 215, 215))))
        );
        background1Layout.setVerticalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_x2w2_or, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(527, 527, 527))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_alpha_or, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txt_th_or, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(background1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_epoch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(background1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(background1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_x1_or, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background1Layout.createSequentialGroup()
                        .addComponent(txt_w1_or, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background1Layout.createSequentialGroup()
                        .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_error_or, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))))
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_f_or, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(background1Layout.createSequentialGroup()
                        .addComponent(txt_x1w1_or, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(background1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(background1Layout.createSequentialGroup()
                                        .addGap(47, 47, 47)
                                        .addComponent(txt_x2_or, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(background1Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(txt_w2_or, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addGap(38, 38, 38)
                                .addComponent(training_or))
                            .addGroup(background1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel9))))
                    .addComponent(txt_y_or, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(351, 351, 351))
        );

        jTabbedPane1.addTab("Single Layer Perceptron", background1);

        txt_x1_xor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_x1_xorActionPerformed(evt);
            }
        });

        jLabel37.setText("X1");

        jLabel38.setText("X2");

        txt_h2_xor.setEditable(false);
        txt_h2_xor.setBackground(new java.awt.Color(255, 255, 255));
        txt_h2_xor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_h2_xorActionPerformed(evt);
            }
        });

        jLabel40.setText("V1");

        txt_h1_xor.setEditable(false);
        txt_h1_xor.setBackground(new java.awt.Color(255, 255, 255));
        txt_h1_xor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_h1_xorActionPerformed(evt);
            }
        });

        jLabel39.setText("V1");

        txt_out_xor.setEditable(false);
        txt_out_xor.setBackground(new java.awt.Color(255, 255, 255));
        txt_out_xor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_out_xorActionPerformed(evt);
            }
        });

        txt_target_xor.setEditable(false);
        txt_target_xor.setBackground(new java.awt.Color(255, 255, 255));
        txt_target_xor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_target_xorActionPerformed(evt);
            }
        });

        jLabel34.setText("alpha");

        jLabel35.setText("treshold");

        jButton1.setText("TRAINING");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel12.setText("w11");

        jLabel13.setText("w12");

        jLabel14.setText("w21");

        jLabel15.setText("W22");

        jLabel16.setText("w31");

        jLabel17.setText("w32");

        jLabel41.setText("error");

        txt_error_xor.setEditable(false);
        txt_error_xor.setBackground(new java.awt.Color(255, 255, 255));

        jLabel18.setText("Target");

        javax.swing.GroupLayout backgroundxor1Layout = new javax.swing.GroupLayout(backgroundxor1);
        backgroundxor1.setLayout(backgroundxor1Layout);
        backgroundxor1Layout.setHorizontalGroup(
            backgroundxor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundxor1Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel38)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(backgroundxor1Layout.createSequentialGroup()
                .addGroup(backgroundxor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundxor1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addGap(4, 4, 4))
                    .addGroup(backgroundxor1Layout.createSequentialGroup()
                        .addGroup(backgroundxor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backgroundxor1Layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addGroup(backgroundxor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(backgroundxor1Layout.createSequentialGroup()
                                        .addGroup(backgroundxor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txt_x1_xor, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                                            .addComponent(txt_x2_xor))
                                        .addGroup(backgroundxor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(backgroundxor1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel12))
                                            .addGroup(backgroundxor1Layout.createSequentialGroup()
                                                .addGap(28, 28, 28)
                                                .addGroup(backgroundxor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel13)
                                                    .addGroup(backgroundxor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txt_w12_xor, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txt_w11_xor, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                    .addGroup(backgroundxor1Layout.createSequentialGroup()
                                        .addGap(80, 80, 80)
                                        .addComponent(txt_w21_xor, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel37)))
                            .addGroup(backgroundxor1Layout.createSequentialGroup()
                                .addGap(162, 162, 162)
                                .addGroup(backgroundxor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_w22_xor, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)))
                .addGap(3, 3, 3)
                .addGroup(backgroundxor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(backgroundxor1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(backgroundxor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_out_xor, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_th_xor, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(93, 93, 93)
                        .addComponent(txt_target_xor, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(backgroundxor1Layout.createSequentialGroup()
                        .addGroup(backgroundxor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(backgroundxor1Layout.createSequentialGroup()
                                .addGroup(backgroundxor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel40)
                                    .addComponent(jLabel34))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_alpha_xor, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel39)
                            .addComponent(txt_h1_xor, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, backgroundxor1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(txt_h2_xor, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(2, 2, 2)
                        .addGroup(backgroundxor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backgroundxor1Layout.createSequentialGroup()
                                .addComponent(jLabel35)
                                .addGap(131, 131, 131))
                            .addGroup(backgroundxor1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(backgroundxor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_w31_xor, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17)
                                    .addComponent(txt_w32_xor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(backgroundxor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(backgroundxor1Layout.createSequentialGroup()
                                        .addGap(59, 59, 59)
                                        .addComponent(jLabel41)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_error_xor, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(131, 131, 131))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundxor1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel18)
                                        .addContainerGap())))))))
        );
        backgroundxor1Layout.setVerticalGroup(
            backgroundxor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundxor1Layout.createSequentialGroup()
                .addGroup(backgroundxor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundxor1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(backgroundxor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel34)
                            .addComponent(txt_alpha_xor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel35)
                            .addComponent(txt_th_xor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addComponent(jLabel37)
                        .addGroup(backgroundxor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(backgroundxor1Layout.createSequentialGroup()
                                .addGroup(backgroundxor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(backgroundxor1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_x1_xor, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(backgroundxor1Layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_w11_xor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(24, 24, 24)
                                        .addComponent(jLabel13)))
                                .addGap(4, 4, 4)
                                .addComponent(txt_w12_xor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(backgroundxor1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel39)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(backgroundxor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundxor1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_w31_xor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txt_h1_xor, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17)
                        .addGap(6, 6, 6)
                        .addComponent(txt_w32_xor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundxor1Layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(backgroundxor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_target_xor, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_out_xor, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(backgroundxor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel41)
                            .addComponent(txt_error_xor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(backgroundxor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundxor1Layout.createSequentialGroup()
                        .addComponent(txt_h2_xor, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addGroup(backgroundxor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backgroundxor1Layout.createSequentialGroup()
                                .addComponent(txt_x2_xor, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel38)
                                .addGap(8, 8, 8)
                                .addComponent(jButton1))
                            .addGroup(backgroundxor1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel40)))
                        .addContainerGap(27, Short.MAX_VALUE))
                    .addGroup(backgroundxor1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_w21_xor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_w22_xor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("Multi Layer Perceptron", backgroundxor1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_h1_xorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_h1_xorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_h1_xorActionPerformed

    private void txt_h2_xorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_h2_xorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_h2_xorActionPerformed

    private void txt_out_xorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_out_xorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_out_xorActionPerformed

    private void txt_target_xorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_target_xorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_target_xorActionPerformed

    private void txt_x1_xorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_x1_xorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_x1_xorActionPerformed

    private void training_orActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_training_orActionPerformed
        // TODO add your handling code here:
        try {

            this.setInput();
            switch (jComboBox1.getSelectedIndex()) {
                case 0:
                    this.setTarget(new int[]{1, 1, 1, 0});
                    break;
                case 1:
                    this.setTarget(new int[]{1, 0, 0, 0});
                    break;
                case 2:
                    this.setTarget(new int[]{0, 1, 0, 1});
                    break;
            }

            this.setAlpha(Double.parseDouble(getTxt_alpha_or().getText()));
            this.setThreshold(Integer.parseInt(getTxt_th_or().getText()));
            this.setW1(Double.parseDouble(getTxt_w1_or().getText()));
            this.setW2(Double.parseDouble(getTxt_w2_or().getText()));

            training_or.setEnabled(false);

            new Timer().schedule(new Task(this), 2000, INTERVAL * 1000);



        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Silahkan Isi w1, w2, alpha dan threshold");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_training_orActionPerformed

    private void txt_x2w2_orActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_x2w2_orActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_x2w2_orActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.inputnode = new ArrayList<InputNode>();
        inputnode.add(new InputNode(1));
        inputnode.add(new InputNode(1));
        
         this.targetnode = new ArrayList<TargetNode>();
        targetnode.add(new TargetNode(0));
        
        this.hidden = new ArrayList<HiddenNode>();
        hidden.add(new HiddenNode(0, "Hidden 1"));
        hidden.add(new HiddenNode(0, "Hidden 2"));
        
        this.output = new ArrayList<OutputNode>();
        output.add(new OutputNode(0, "output 1"));
        
        for (int i = 0; i < output.size(); i++) {
            output.get(i).setNodeTarget(targetnode.get(i));
        }

        this.bobotHide = new ArrayList<Bobot>();
        int x = 0;
        for (int i = 0; i < inputnode.size(); i++) {
            for (int ii = 0; ii < hidden.size(); ii++) {
                bobotHide.add(new Bobot("bobotHideArray[" + i + "] [" + ii + "]"));
                bobotHide.get(x).setNodeInput(inputnode.get(i));
                bobotHide.get(x).setNodeTarget(hidden.get(ii));
                //menambahkan bobot input untuk hidden layer dari layer input
                hidden.get(ii).addBobotIn(bobotHide.get(x));
                x++;

            }
        }

        this.bobotOut = new ArrayList<Bobot>();
        x = 0;
        for (int i = 0; i < hidden.size(); i++) {
            for (int ii = 0; ii < output.size(); ii++) {
                bobotOut.add(new Bobot("bobotOutArray[" + i + "] [" + ii + "]"));
                bobotOut.get(x).setNodeInput(hidden.get(i));
                bobotOut.get(x).setNodeTarget(output.get(ii));
                //menambahkan bobotInput untuk output layer dari hiden layer
                output.get(ii).addBobotIn(bobotOut.get(x));
                //menambahkan output bobot pada hidden layer ke output layer
                hidden.get(i).getBobotOut().add(bobotOut.get(x));
                x++;
            }
        }
        
        this.bobotHide.get(0).setBobot(Double.parseDouble(txt_w11_xor.getText()));
        this.bobotHide.get(1).setBobot(Double.parseDouble(txt_w12_xor.getText()));
        this.bobotHide.get(2).setBobot(Double.parseDouble(txt_w21_xor.getText()));
        this.bobotHide.get(3).setBobot(Double.parseDouble(txt_w22_xor.getText()));
        
        this.bobotOut.get(0).setBobot(Double.parseDouble(txt_w31_xor.getText()));
        this.bobotOut.get(1).setBobot(Double.parseDouble(txt_w32_xor.getText()));
        
        this.inputArray=new int[4][2];
        this.inputArray[0]=new int[]{1,1};
        this.inputArray[1]=new int[]{1,0};
        this.inputArray[2]=new int[]{0,1};
        this.inputArray[3]=new int[]{0,0};
        
        this.targetArray=new int[4][1];
        this.targetArray[0]=new int[]{0};
        this.targetArray[1]=new int[]{1};
        this.targetArray[2]=new int[]{1};
        this.targetArray[3]=new int[]{0};
        
        new Timer().schedule(new Task2(this), 1000,20);
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private background background1;
    private backgroundxor backgroundxor1;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JLabel lbl_epoch;
    private javax.swing.JButton training_or;
    private javax.swing.JTextField txt_alpha_or;
    private javax.swing.JTextField txt_alpha_xor;
    private javax.swing.JTextField txt_error_or;
    public javax.swing.JTextField txt_error_xor;
    private javax.swing.JTextField txt_f_or;
    public javax.swing.JTextField txt_h1_xor;
    public javax.swing.JTextField txt_h2_xor;
    public javax.swing.JTextField txt_out_xor;
    public javax.swing.JTextField txt_target_xor;
    private javax.swing.JTextField txt_th_or;
    private javax.swing.JTextField txt_th_xor;
    public javax.swing.JTextField txt_w11_xor;
    public javax.swing.JTextField txt_w12_xor;
    private javax.swing.JTextField txt_w1_or;
    public javax.swing.JTextField txt_w21_xor;
    public javax.swing.JTextField txt_w22_xor;
    private javax.swing.JTextField txt_w2_or;
    public javax.swing.JTextField txt_w31_xor;
    public javax.swing.JTextField txt_w32_xor;
    private javax.swing.JTextField txt_x1_or;
    public javax.swing.JTextField txt_x1_xor;
    private javax.swing.JTextField txt_x1w1_or;
    private javax.swing.JTextField txt_x2_or;
    public javax.swing.JTextField txt_x2_xor;
    private javax.swing.JTextField txt_x2w2_or;
    private javax.swing.JTextField txt_y_or;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the jTextField1
     */
    public javax.swing.JTextField getjTextField1() {
        return txt_x1_xor;
    }

    /**
     * @param jTextField1 the jTextField1 to set
     */
    public void setjTextField1(javax.swing.JTextField jTextField1) {
        this.txt_x1_xor = jTextField1;
    }

    /**
     * @return the jTextField2
     */
    public javax.swing.JTextField getjTextField2() {
        return txt_x2_xor;
    }

    /**
     * @param jTextField2 the jTextField2 to set
     */
    public void setjTextField2(javax.swing.JTextField jTextField2) {
        this.txt_x2_xor = jTextField2;
    }

    /**
     * @return the jTextField3
     */
    public javax.swing.JTextField getjTextField3() {
        return txt_target_xor;
    }

    /**
     * @param jTextField3 the jTextField3 to set
     */
    public void setjTextField3(javax.swing.JTextField jTextField3) {
        this.txt_target_xor = jTextField3;
    }

    /**
     * @return the jTextField4
     */
    public javax.swing.JTextField getjTextField4() {
        return txt_out_xor;
    }

    /**
     * @param jTextField4 the jTextField4 to set
     */
    public void setjTextField4(javax.swing.JTextField jTextField4) {
        this.txt_out_xor = jTextField4;
    }

    /**
     * @return the jTextField5
     */
    public javax.swing.JTextField getjTextField5() {
        return txt_h2_xor;
    }

    /**
     * @param jTextField5 the jTextField5 to set
     */
    public void setjTextField5(javax.swing.JTextField jTextField5) {
        this.txt_h2_xor = jTextField5;
    }

    /**
     * @return the jTextField6
     */
    public javax.swing.JTextField getjTextField6() {
        return txt_h1_xor;
    }

    /**
     * @param jTextField6 the jTextField6 to set
     */
    public void setjTextField6(javax.swing.JTextField jTextField6) {
        this.txt_h1_xor = jTextField6;
    }

    /**
     * @return the training_or
     */
    public javax.swing.JButton getTraining_or() {
        return training_or;
    }

    /**
     * @param training_or the training_or to set
     */
    public void setTraining_or(javax.swing.JButton training_or) {
        this.training_or = training_or;
    }  

    /**
     * @return the txt_alpha_or
     */
    public javax.swing.JTextField getTxt_alpha_or() {
        return txt_alpha_or;
    }

    /**
     * @param txt_alpha_or the txt_alpha_or to set
     */
    public void setTxt_alpha_or(javax.swing.JTextField txt_alpha_or) {
        this.txt_alpha_or = txt_alpha_or;
    }

    /**
     * @return the txt_alpha_xor
     */
    public javax.swing.JTextField getTxt_alpha_xor() {
        return txt_alpha_xor;
    }

    /**
     * @param txt_alpha_xor the txt_alpha_xor to set
     */
    public void setTxt_alpha_xor(javax.swing.JTextField txt_alpha_xor) {
        this.txt_alpha_xor = txt_alpha_xor;
    }


  
  

    /**
     * @return the txt_error_or
     */
    public javax.swing.JTextField getTxt_error_or() {
        return txt_error_or;
    }

    /**
     * @param txt_error_or the txt_error_or to set
     */
    public void setTxt_error_or(String txt_error_or) {
        this.txt_error_or.setText(txt_error_or);
    }

    /**
     * @return the txt_error_xor
     */

   

   
    /**
     * @return the txt_f_or
     */
    public javax.swing.JTextField getTxt_f_or() {
        return txt_f_or;
    }

    /**
     * @param txt_f_or the txt_f_or to set
     */
    public void setTxt_f_or(String txt_f_or) {
        this.txt_f_or.setText(txt_f_or);
    }


    /**
     * @return the txt_th_or
     */
    public javax.swing.JTextField getTxt_th_or() {
        return txt_th_or;
    }

    /**
     * @param txt_th_or the txt_th_or to set
     */
    public void setTxt_th_or(javax.swing.JTextField txt_th_or) {
        this.txt_th_or = txt_th_or;
    }

    /**
     * @return the txt_th_xor
     */
    public javax.swing.JTextField getTxt_th_xor() {
        return txt_th_xor;
    }

    /**
     * @param txt_th_xor the txt_th_xor to set
     */
    public void setTxt_th_xor(javax.swing.JTextField txt_th_xor) {
        this.txt_th_xor = txt_th_xor;
    }

  
    /**
     * @return the txt_w1_or
     */
    public javax.swing.JTextField getTxt_w1_or() {
        return txt_w1_or;
    }

    /**
     * @param txt_w1_or the txt_w1_or to set
     */
    public void setTxt_w1_or(String txt_w1_or) {
        this.txt_w1_or.setText(txt_w1_or);
    }

   


    /**
     * @return the txt_w2_or
     */
    public javax.swing.JTextField getTxt_w2_or() {
        return txt_w2_or;
    }

    /**
     * @param txt_w2_or the txt_w2_or to set
     */
    public void setTxt_w2_or(String txt_w2_or) {
        this.txt_w2_or.setText(txt_w2_or);
    }

   

  

  

  
    /**
     * @return the txt_x1_or
     */
    public javax.swing.JTextField getTxt_x1_or() {
        return txt_x1_or;
    }

    /**
     * @param txt_x1_or the txt_x1_or to set
     */
    public void setTxt_x1_or(String txt_x1_or) {
        this.txt_x1_or.setText(txt_x1_or);
    }

  

  

  

    /**
     * @return the txt_x1w1_or
     */
    public javax.swing.JTextField getTxt_x1w1_or() {
        return txt_x1w1_or;
    }

    /**
     * @param txt_x1w1_or the txt_x1w1_or to set
     */
    public void setTxt_x1w1_or(String txt_x1w1_or) {
        this.txt_x1w1_or.setText(txt_x1w1_or);
    }

  

 

    /**
     * @return the txt_x2_or
     */
    public javax.swing.JTextField getTxt_x2_or() {
        return txt_x2_or;
    }

    /**
     * @param txt_x2_or the txt_x2_or to set
     */
    public void setTxt_x2_or(String txt_x2_or) {
        this.txt_x2_or.setText(txt_x2_or);
    }

   
    /**
     * @return the txt_x2w2_or
     */
    public javax.swing.JTextField getTxt_x2w2_or() {
        return txt_x2w2_or;
    }

    /**
     * @param txt_x2w2_or the txt_x2w2_or to set
     */
    public void setTxt_x2w2_or(String txt_x2w2_or) {
        this.txt_x2w2_or.setText(txt_x2w2_or);
    }


    /**
     * @return the txt_y_or
     */
    public javax.swing.JTextField getTxt_y_or() {
        return txt_y_or;
    }

    /**
     * @param txt_y_or the txt_y_or to set
     */
    public void setTxt_y_or(String txt_y_or) {
        this.txt_y_or.setText(txt_y_or);
    }
}
